---
repositories:
  cranium/src/corti:
    type: git
    url: git@github.com:CogniPilot/corti
    version: 1a76ee207753bf2efb21a7db636079dcf065605d
  cranium/src/synapse_msgs:
    type: git
    url: git@github.com:CogniPilot/synapse_msgs
    version: 2b4d5a84ef79338ae91c878686300ebcfa6d114d
  cranium/src/synapse_protobuf:
    type: git
    url: git@github.com:CogniPilot/synapse_protobuf
    version: e40ad09f6ab2ff2fd71b1fb7b8621b474f43cc35
  cranium/src/synapse_ros:
    type: git
    url: git@github.com:CogniPilot/synapse_ros
    version: 17b6c2709a5a8cb4c8a2cf290a7061d048f28b22
  cranium/src/synapse_tinyframe:
    type: git
    url: git@github.com:CogniPilot/synapse_tinyframe
    version: 8ea7c6ab3c5cc60a28fe7d5553a4d12f3a85bbec
