---
repositories:
  cranium/src/cerebri_bringup:
    type: git
    url: git@github.com:CogniPilot/cerebri_bringup
    version: brave_rc1
  cranium/src/corti:
    type: git
    url: git@github.com:CogniPilot/corti
    version: brave_rc1
  cranium/src/cyecca:
    type: git
    url: git@github.com:CogniPilot/cyecca
    version: brave_rc1
  cranium/src/dream_world:
    type: git
    url: git@github.com:CogniPilot/dream_world
    version: brave_rc1
  cranium/src/synapse_gz:
    type: git
    url: git@github.com:CogniPilot/synapse_gz
    version: brave_rc1
  cranium/src/synapse_msgs:
    type: git
    url: git@github.com:CogniPilot/synapse_msgs
    version: brave_rc1
  cranium/src/synapse_pb:
    type: git
    url: git@github.com:CogniPilot/synapse_pb
    version: brave_rc1
  cranium/src/synapse_ros:
    type: git
    url: git@github.com:CogniPilot/synapse_ros
    version: brave_rc1
  electrode/src/electrode:
    type: git
    url: git@github.com:CogniPilot/electrode
    version: brave_rc1
  ws/cerebri:
    type: git
    url: git@github.com:CogniPilot/cerebri
    version: brave_rc1

