---
repositories:
  cranium/src/cerebri_bringup:
    type: git
    url: git@github.com:CogniPilot/cerebri_bringup
    version: brave
  cranium/src/corti:
    type: git
    url: git@github.com:CogniPilot/corti
    version: brave
  cranium/src/dream_world:
    type: git
    url: git@github.com:CogniPilot/dream_world
    version: brave
  cranium/src/synapse_gz:
    type: git
    url: git@github.com:CogniPilot/synapse_gz
    version: brave
  cranium/src/synapse_msgs:
    type: git
    url: git@github.com:CogniPilot/synapse_msgs
    version: brave
  cranium/src/synapse_protobuf:
    type: git
    url: git@github.com:CogniPilot/synapse_protobuf
    version: brave
  cranium/src/synapse_ros:
    type: git
    url: git@github.com:CogniPilot/synapse_ros
    version: brave
  cranium/src/synapse_tinyframe:
    type: git
    url: git@github.com:CogniPilot/synapse_tinyframe
    version: brave
  electrode/foxglove-cognipilot-joy:
    type: git
    url: git@github.com:CogniPilot/foxglove-cognipilot-joy
    version: brave
  electrode/src/electrode:
    type: git
    url: git@github.com:CogniPilot/electrode
    version: brave
  tools/src/cyecca:
    type: git
    url: git@github.com:CogniPilot/cyecca
    version: brave
  ws/cerebri:
    type: git
    url: git@github.com:CogniPilot/cerebri
    version: brave

