---
repositories:
  cranium/src/corti:
    type: git
    url: git@github.com:CogniPilot/corti
    version: main
  cranium/src/ros2_psutil_msgs:
    type: git
    url: git@github.com:CogniPilot/ros2_psutil_msgs
    version: main
  cranium/src/ros2_psutil:
    type: git
    url: git@github.com:CogniPilot/ros2_psutil
    version: main
  cranium/src/synapse_msgs:
    type: git
    url: git@github.com:CogniPilot/synapse_msgs
    version: main
  cranium/src/synapse_pb:
    type: git
    url: git@github.com:CogniPilot/synapse_pb
    version: main
  cranium/src/synapse_ros:
    type: git
    url: git@github.com:CogniPilot/synapse_ros
    version: main