#!/bin/bash
if [ ! -d /opt/poetry/bin ] ; then
  echo "please install poetry using helmet/install/scripts/poetry.sh"
  exit 1
fi
if [ ! -f ~/cognipilot/tools/src/cyecca/.venv/bin/python3 ] ; then
  poetry install -C ~/cognipilot/tools/src/cyecca
fi
source ~/cognipilot/tools/src/cyecca/.venv/bin/activate
python3 $@
