#!/bin/bash
if [ ! -d /opt/poetry/bin ] ; then
  echo "please install poetry using helmet/install/scripts/poetry.sh"
  exit 1
fi
poetry install -C ~/cognipilot/tools/src/cyecca
poetry run -C ~/cognipilot/tools/src/cyecca python3 $@
