---
repositories:
  cranium/src/corti:
    type: git
    url: https://github.com/CogniPilot/corti.git
    version: airy
  cranium/src/synapse_msgs:
    type: git
    url: https://github.com/CogniPilot/synapse_msgs.git
    version: airy
  cranium/src/synapse_protobuf:
    type: git
    url: https://github.com/CogniPilot/synapse_protobuf.git
    version: airy
  cranium/src/synapse_ros:
    type: git
    url: https://github.com/CogniPilot/synapse_ros.git
    version: airy
  cranium/src/synapse_tinyframe:
    type: git
    url: https://github.com/CogniPilot/synapse_tinyframe.git
    version: airy
