---
repositories:
  cranium/src/corti:
    type: git
    url: https://github.com/CogniPilot/corti.git
    version: brave_rc1
  cranium/src/ros2_psutil_msgs:
    type: git
    url: https://github.com/CogniPilot/ros2_psutil_msgs
    version: main
  cranium/src/ros2_psutil:
    type: git
    url: https://github.com/CogniPilot/ros2_psutil
    version: main
  cranium/src/synapse_msgs:
    type: git
    url: https://github.com/CogniPilot/synapse_msgs.git
    version: brave_rc1
  cranium/src/synapse_pb:
    type: git
    url: https://github.com/CogniPilot/synapse_pb.git
    version: brave_rc1
  cranium/src/synapse_ros:
    type: git
    url: https://github.com/CogniPilot/synapse_ros.git
    version: brave_rc1
